# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/beus/cxx/hw5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/beus/cxx/hw5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beus/cxx/hw5/CMakeFiles /home/beus/cxx/hw5//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beus/cxx/hw5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named builder

# Build rule for target.
builder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 builder
.PHONY : builder

# fast build rule for target.
builder/fast:
	$(MAKE) $(MAKESILENT) -f model/builder/CMakeFiles/builder.dir/build.make model/builder/CMakeFiles/builder.dir/build
.PHONY : builder/fast

#=============================================================================
# Target rules for targets named grades

# Build rule for target.
grades: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grades
.PHONY : grades

# fast build rule for target.
grades/fast:
	$(MAKE) $(MAKESILENT) -f model/grades/CMakeFiles/grades.dir/build.make model/grades/CMakeFiles/grades.dir/build
.PHONY : grades/fast

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) $(MAKESILENT) -f model/project/CMakeFiles/project.dir/build.make model/project/CMakeFiles/project.dir/build
.PHONY : project/fast

#=============================================================================
# Target rules for targets named student

# Build rule for target.
student: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 student
.PHONY : student

# fast build rule for target.
student/fast:
	$(MAKE) $(MAKESILENT) -f model/student/abstract_student/CMakeFiles/student.dir/build.make model/student/abstract_student/CMakeFiles/student.dir/build
.PHONY : student/fast

#=============================================================================
# Target rules for targets named junior

# Build rule for target.
junior: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 junior
.PHONY : junior

# fast build rule for target.
junior/fast:
	$(MAKE) $(MAKESILENT) -f model/student/junior/CMakeFiles/junior.dir/build.make model/student/junior/CMakeFiles/junior.dir/build
.PHONY : junior/fast

#=============================================================================
# Target rules for targets named senior

# Build rule for target.
senior: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 senior
.PHONY : senior

# fast build rule for target.
senior/fast:
	$(MAKE) $(MAKESILENT) -f model/student/senior/CMakeFiles/senior.dir/build.make model/student/senior/CMakeFiles/senior.dir/build
.PHONY : senior/fast

#=============================================================================
# Target rules for targets named graduate

# Build rule for target.
graduate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graduate
.PHONY : graduate

# fast build rule for target.
graduate/fast:
	$(MAKE) $(MAKESILENT) -f model/student/graduate/CMakeFiles/graduate.dir/build.make model/student/graduate/CMakeFiles/graduate.dir/build
.PHONY : graduate/fast

#=============================================================================
# Target rules for targets named in_memory_repository

# Build rule for target.
in_memory_repository: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 in_memory_repository
.PHONY : in_memory_repository

# fast build rule for target.
in_memory_repository/fast:
	$(MAKE) $(MAKESILENT) -f repository/in_memory_repository/CMakeFiles/in_memory_repository.dir/build.make repository/in_memory_repository/CMakeFiles/in_memory_repository.dir/build
.PHONY : in_memory_repository/fast

#=============================================================================
# Target rules for targets named university

# Build rule for target.
university: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 university
.PHONY : university

# fast build rule for target.
university/fast:
	$(MAKE) $(MAKESILENT) -f service/university/CMakeFiles/university.dir/build.make service/university/CMakeFiles/university.dir/build
.PHONY : university/fast

#=============================================================================
# Target rules for targets named cli_controller

# Build rule for target.
cli_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cli_controller
.PHONY : cli_controller

# fast build rule for target.
cli_controller/fast:
	$(MAKE) $(MAKESILENT) -f controller/cli_controller/CMakeFiles/cli_controller.dir/build.make controller/cli_controller/CMakeFiles/cli_controller.dir/build
.PHONY : cli_controller/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) $(MAKESILENT) -f application/CMakeFiles/application.dir/build.make application/CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named my_app

# Build rule for target.
my_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_app
.PHONY : my_app

# fast build rule for target.
my_app/fast:
	$(MAKE) $(MAKESILENT) -f application/CMakeFiles/my_app.dir/build.make application/CMakeFiles/my_app.dir/build
.PHONY : my_app/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... application"
	@echo "... builder"
	@echo "... cli_controller"
	@echo "... grades"
	@echo "... graduate"
	@echo "... in_memory_repository"
	@echo "... junior"
	@echo "... my_app"
	@echo "... project"
	@echo "... senior"
	@echo "... student"
	@echo "... university"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

